lesson:
  size: 10
user:
  per_page: 10
category:
  per_page: 15
image: "img.jpg"
all_users: "all_users"
all_categories: "all_categories"
word:
  per_page: 15
  filters:
    - all_words
    - learnt
    - not_yet
following:
  per_page: 10
follower:
  per_page: 10
activity:
  size: 10
  per_page: 10
first_mark: 5
second_mark: 9
bad: "Bad(0-4)"
good: "Good(5-8)"
excellent: "Excellent(9-10)"
date_format: "%Y-%m-%d"
weekday: 7
one: 1
eight: 8
